app <- ShinyDriver$new("../")
app$snapshotInit("test_cyper_NOEC_filter")

# Input 'contents_rows_current' was set, but doesn't have an input binding.
# Input 'contents_rows_all' was set, but doesn't have an input binding.
app$setInputs(navbar = "SSD")
app$setInputs(sps_group = c("Algae, Moss, Fungi", "Amphibians", "Crustaceans", "Fish", "Flowers, Trees, Shrubs, Ferns", "Insects/Spiders", "Invertebrates"))
app$setInputs(effect = c("Biochemistry", "Population", "Enzyme(s)", "Development", "Mortality", "Reproduction", "Feeding behavior", "Behavior", "Multiple or Undefined", "Growth", "Cell(s)", "Genetics", "Injury", "Histology", "Intoxication", "Hormone(s)", "Morphology", "Immunological"))
app$setInputs(analytic_validation = c("Unmeasured", "Measured", "Not coded"))
app$setInputs(chem_type = "Active ingredient")
app$setInputs(exp_type = c("Static", "Aquatic - not reported", "Renewal", "Lentic", "Pulse", "Flow-through", "Lotic"))
app$setInputs(media_type = c("Freshwater", "Saltwater"))
app$setInputs(org_lifestage = c("Exponential growth phase (log)", "Not reported", "Egg(s)", "Juvenile(s)", "Adult(s)", "Organisms at different lifestages", "Larva(e)", "Neonate", "Not coded", "F1 generation", "Embryo(s)", "Morula", "Not intact", "Mature organism(s)", "Fry", "Sexually mature organism(s)", "Smolt", "Nymph(s)"))
app$setInputs(tabsetpanel = "Goodness of Fit")
app$snapshot()
app$setInputs(tabsetpanel = "Visualization")
app$snapshot()
app$setInputs(tabsetpanel = "HC5 and Plot", timeout_ = 10000)
app$snapshot(list(output = "coolplot"))
app$snapshot(list(output = "hc5"))
app$snapshot(list(output = "bestfit2"))
